const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.MoveTo,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.Pin,
		C3.Behaviors.Bullet,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.solid,
		C3.Behaviors.Flash,
		C3.Behaviors.Fade,
		C3.Behaviors.custom,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Touch,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.custom.Acts.PushOutSolid,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Behaviors.scrollto.Acts.Shake,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.OnAnimFinished
	];
};
self.C3_JsPropNameTable = [
	{MoveTo: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Ship: 0},
	{Pin: 0},
	{Turret: 0},
	{Bullet: 0},
	{PlayerBullet: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{CrossHair: 0},
	{ShipHealth: 0},
	{Pathfinding: 0},
	{Solid: 0},
	{Flash: 0},
	{Fade: 0},
	{Custom: 0},
	{Enemy: 0},
	{Sprite: 0},
	{Health: 0},
	{Enemy2: 0},
	{tankbullet: 0},
	{Audio: 0},
	{ID: 0},
	{spawnPoint: 0},
	{Text: 0},
	{InitialWidth: 0},
	{HealthBar: 0},
	{Text2: 0},
	{PowerUp: 0},
	{Sine: 0},
	{potion1: 0},
	{spawn: 0},
	{tyler: 0},
	{play: 0},
	{Text4: 0},
	{Touch: 0},
	{tankbullet2: 0},
	{PlayerBullet2: 0},
	{Sprite2: 0},
	{Particles: 0},
	{Sprite3: 0},
	{floortexture: 0},
	{PlayerHealth: 0},
	{EnemyShootTime: 0},
	{Score: 0},
	{SpawnSpeed: 0},
	{spawnerRNG: 0},
	{HealthMax: 0},
	{potionSpeed: 0},
	{potionRNG: 0}
];

self.InstanceType = {
	Ship: class extends self.ISpriteInstance {},
	Turret: class extends self.ISpriteInstance {},
	PlayerBullet: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	CrossHair: class extends self.ISpriteInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Enemy2: class extends self.ISpriteInstance {},
	tankbullet: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	spawnPoint: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	HealthBar: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	PowerUp: class extends self.ISpriteInstance {},
	potion1: class extends self.ISpriteInstance {},
	spawn: class extends self.ISpriteInstance {},
	tyler: class extends self.ISpriteInstance {},
	play: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	Touch: class extends self.IInstance {},
	tankbullet2: class extends self.ISpriteInstance {},
	PlayerBullet2: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Particles: class extends self.IParticlesInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	floortexture: class extends self.ISpriteInstance {}
}